### ISSUE TITLE
Pretrained checkpoints hyperparameters

### ISSUE THREAD

**Issue by Laope94** [rhasspy/piper#155]
Hi,
are hyperparameters that were used to train checkpoints at https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main documented somewhere? Or were it always parameters as seen in VitsModel class in lightning.py without change?

**Comment by synesthesiam** [comment]
The hyperparameters are embedding in the checkpoint, but you can also see the defaults here: https://github.com/rhasspy/piper/blob/master/src/python/piper_train/vits/config.py

The different quality levels will change some hyper parameters in the audio config, but otherwise everything is kept the same.
