### ISSUE TITLE
Could not find a version that satisfies the requirement piper-phonemize~=1.0.0

### ISSUE THREAD

**Issue by rtruszkowski** [rhasspy/piper#157]
```
❯ pip install piper-tts
Collecting piper-tts
  Obtaining dependency information for piper-tts from https://files.pythonhosted.org/packages/2e/1c/cc3a342db7f03053eca4fa5b05362178a5a796115770b216740b733b24d7/piper_tts-1.1.0-py3-none-any.whl.metadata
  Using cached piper_tts-1.1.0-py3-none-any.whl.metadata (776 bytes)
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.0.0 (from piper-tts) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.0.0
~/Developer/piper-tts ❯
```

I was unable to find a way to get this installed. What am I missing? 🤔 

Same issue when I just try to pip install `piper-phonemize` directly.

**Comment by rtruszkowski** [comment]
Currently this is supported on LINUX with Python version 3.9 - 3.11.

I was using 3.8. 

Problem solved =) Thanks to @ThorstenMueller on YT.

**Comment by patchworquill** [comment]
I'm getting this error In python 3.11.4 with pip 23.2.1.

**Comment by rtruszkowski** [comment]
> piper-phonemize

Which architecture are you on?

https://github.com/rhasspy/piper-phonemize/releases/tag/v1.1.0

The release shows 3.9, 3.10 and 3.11 wheels for aarch64 and x86_64

**Comment by FotieMConstant** [comment]
Just tried install this on Apple Silicon M1 and got this error, any fix please?

**Comment by DoS007** [comment]
pip install piper-tts gives me ERROR: No matching distribution found for piper-phonemize~=1.1.0

**Comment by kqdlx3** [comment]
get the same error in python3.10.14, x86_64, what a rubbish project

**Comment by kqdlx3** [comment]
> Alternatively, if a binary is not available, you can always try building the package yourself. Clone piper-phonemize, build it, and change your project's requirements.txt from `piper-phonemize~=1.1.0` to `-e <path_to_your_local_version>`. The syntax should be correct... 🤔

not work

**Comment by rodyherrera** [comment]
Hello, I got the same problem after trying to install **piper-tts** through pipy using the latest version of python, **3.12**. 

As you can see in the image, the error occurs, however, if I install the library using pipy in python 3.10 using the command "python3.10 -m pip install piper-tts" the error is not triggered. 

Maybe it's because of the Python version?

I hope it helps something :).

![Screenshot from 2024-07-22 00-23-59](https://github.com/user-attachments/assets/e782d1d2-f548-4de7-8056-c219f25888c8)
(Screenshot with the error using Python 3.12)

![Screenshot from 2024-07-22 00-24-13](https://github.com/user-attachments/assets/4fb0d42b-81f5-42d0-9383-3099aac7155e)
(Screenshot where the error is not triggered after executing the installation from Python 3.10)

**Comment by ekcrisp** [comment]
I am getting this error on latest Ubuntu (24 lts) and latest python (3.12). I was able to install by using pyenv to downgrade to python 3.9.  This is something the project maintainers need to prioritize, using the latest software should work on a project that is under active development, or if it doesn't work that needs to be called out in documentation.

**Comment by Planze** [comment]
I have tried python 3.9, 3.10 as well as 3.11, and a few in between . Have not got it to work. Is there a specific version this is built upon? Have you guys found a solution on this yet? I am also on windows.

Someone above commented this could be avoided by building it from source. Could anyone point me in a direction on how that could be achieved if this is to be used in a python script?

**Comment by brandyn** [comment]
I was able to get piper-tts installed on the latest Ubuntu LTS under python3.12 by downloading an older version of the project from github and changing one line of the Dockerfile to compile a python 3.12 version.  Here are the exact commands I issued in order (since it builds with docker, this should be fairly independent of your particular environ?).  I did these as a regular user, not root.  You will need to have docker.io installed and your user must be in the docker group:

1.     git clone https://github.com/rhasspy/piper-phonemize.git
2.     cd piper-phonemize
3.     git checkout 20554f24f807146fcf183f4a22ac10e9f24c9f45     # Last checkin with 1.1.0 tag?
4.     vi Dockerfile                                             # Add (it's obvious where): /opt/python/cp312-cp312/bin/pip wheel . && \
5.     docker buildx build . -t piper-phonemize --output 'type=local,dest=dist'
6.     cd dist
7.     pip install piper_phonemize-1.1.0-cp312-cp312-manylinux_2_28_x86_64.whl
8.     pip install piper-tts

**Comment by jwarwick-bry** [comment]
I am also getting the error from within container from: docker.io/library/ubuntu:latest , which at this point in time is:
Ubuntu 24.04.1 LTS noble
Python 3.12.3
pip 24.0
I am pretty sure this _was_ working in Docker a few months ago.

**Comment by brandyn** [comment]
The quick fix is to build an older version of piper-phonemize for python12, which is straightforward (you'll need docker-buildx installed but the rest happens inside a container so should replicate easily).  See https://github.com/rhasspy/piper-phonemize/issues/33#issuecomment-2540407032

It's yucky but should "just work", and pulls from the main repository only so should be safe.

Not sure how to do that inside another docker container.  Dockerception?
