### ISSUE TITLE
featurerequest: Prosody or rate control

### ISSUE THREAD

**Issue by d-r-a-b** [rhasspy/piper#16]
Dear @synesthesiam,

Thank you so much for creating this and making it available. publicly I apologize if this is not the appropriate place to contact you regarding this, and I should clarify that this is not a true feature request. I have simply tagged it that way so that it has a nicer name in the issue tracker.

I was curious to know if there is any way currently to either tune the network during training, or to adjust larynx2 during operation, to support different rates of speech? I imagine if I were to record an entire speaker's worth of audio at a different rate and train using that, it would create a model that spoke at that different speed. I was just wondering if rate of speech is essentially fixed in these neural model implementations once trained. I am very new to TTS and RNN, and so am not really certain what is technically easy vs feasible but challenging vs impossible.

Thanks to you sharing this code, I am also now seeing what training an RNN might be like and am making headway in setting up training on the LJSpeech dataset to get an idea of how to go about training a voice. How long does your training take per epoch so that I may have a ballpark? At the moment it seems that it will take about 1 hr/epoch for the LJSpeech-1.1 dataset, but I have no frame of reference to determine whether that is fast, slower or about expected. 1000 hours to do 1000 epochs seems like it would be quite a long time to leave this running though. Of course, I know that all of this is relative to the hardware on which things are being run. I am currently running the training through WSL2, with CUDA through a GeForce GTX (not RTX) 1650 on a intel i7-9750. I had to reduce the `batch_size` down to 4 from the suggested 32 just to enable to training steps to run without PyTorch complaining about `RunTime Error: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 3.37 GiB already allocated; 0 bytes free; 3.45 GiB reserved in total by PyTorch).` so I know that there are probably some significant performance hits in general from the WSL2 indirection and from the underspec'ed GPU.

Thank you for any information you have the time to share,
@d-r-a-b

**Comment by d-r-a-b** [comment]
Aha! I have just discovered the `--length-scale` option which answers my main reason for posting this. Thanks again!

I am still curious about the training questions I posed, but I am working through this either way. Thank you for posting the LJSpeech checkpoints as well. Are they worth using as an initial training checkpoint for other voices? If so, is it better for the voices to be tagged specifically as belonging to another speaker?

Thank you again,
@d-r-a-b

**Comment by synesthesiam** [comment]
Hi @d-r-a-b, you're welcome :slightly_smiling_face: 

I would recommend starting with [a checkpoint](https://drive.google.com/drive/folders/1Hd_dP9BpDYbi1enRDEMIN34W1nfIgmp6?usp=sharing) that is for the language you want to train and use `--resume_from_checkpoint` to fine-tune instead of starting from scratch.

4GB isn't a lot of VRAM these days, so it wouldn't surprise me to see it taking an hour for an epoch of the LJSpeech dataset. If you fine-tune instead with a smaller dataset, each epoch should be quicker though.

What language/voice are you wanting to train?

**Comment by d-r-a-b** [comment]
Thank you for your kind reply and suggestions. I am interested in training en-US/en-UK and have been looking around for datasets. My first task was to verify I could even run a training epoch and export an ONNX. I am glad to say I was able to do so with a few modifications to `requirements.txt`. The Lessac ONNX file you provide is already very good, as is the ONNX I was able to export from your LJSpeech/low checkpoint. I must sincerely compliment your work, as I think these voices sound much better already than most TTS I have heard in the past, and certainly better than the default Windows TTS voices or the Festival voices.

I have 2 main uses for TTS at the moment. which I understand deviate from the Rhasspy use case and are likely lower priority from the Rhasspy project perspective. 1) Narrate chapters of eBooks while I do other tasks and 2) dictate passages for practice in shorthand, which is a method of fast writing. I have a bash script which I have used to create files at speeds of 60-140 WPM by feeding larynx2 10-word chunks and inserting silence between those groups to create an effective WPM rate. Where the current Larynx2 voices suffer as compared to a real human, and which I would hope additional training would help improve:

  1. Isolated words sometimes do not sound very good because of missing or altered phonemes.
  2. Sometimes pauses between sentences are shorter than those between words, or to state the reverse, sometimes pauses between words are longer than those between sentences. It can just feel unnatural, although this is emphasized by the contrast in how good Larynx2 already is about this in many places. More noticeable on long passages/books.
  3. Elongated vowels do not seem possible. Like BEEEEEEEEEEEEEEEEEEEP, woooooooooooow, uuuuuuuummmmm, oooookaaaaaaaay. To be honest, I have no expectation of training a solution to this.

As I move forward to pick a dataset and train using a checkpoint, a few questions if you have the time/bandwidth to respond:

  1. Is the Lessac checkpoint also available somewhere? It might be a better starting point if I train a en-UK voice.
  2. Is it a bad idea to train a dataset recorded at 22.050 kHz samplerate, starting from a checkpoint that was training on 16 khz samplerate? In the same way, is it possible to train a multi-speaker dataset at different samplerates or should I take care to re-encode the audio if the rates are different?
  3. If I start with the LJSpeech checkpoint, and want to train e.g. RyanSpeech (a male en-US voice), should I tag all of RyanSpeech as belonging to a different speaker, or just leave it at None? (I had to hack-patch `preprocess.py` since 3 columns in LJSpeech-1.1 does not have speaker in the 2nd column of metadata)
  4. In terms of how multi-speaker models work, is it basically 1 model for each speaker, or is it 1 unified model that uses all speakers to help model the underlying ascii/IPA --> Phoneme Sound mapping?

Thank you again for any help you can offer,
@d-r-a-b

**Comment by synesthesiam** [comment]
The Lessac checkpoint is available here now: https://drive.google.com/drive/folders/1h1RH4ktA-ppDBbBYUMi8HKFrI2xnfTcY?usp=share_link

Isolated words and odd pauses are largely due to the datasets, which often are single sentences from books. To get it right, you need a dataset that has lots of single words, single sentences, and some multiple sentences. Without this, the model can't learn what to do with end of sentence punctuation, etc.

I would stay with the sample rate the original dataset was trained at, but I haven't really experimented with it. I don't think multi-speaker would work at different sample rates, since the mel spectrograms are calculated with it in mind.

For female/male changes, you don't have to re-tag a speaker. In fact, you can fine-tune between languages. I've started with the LJSpeech checkpoint to train many of the other voices from different languages. Regarding the `preprocess.py` hack, I added a `--single-speaker` option to force it to not interpret the second column as a speaker id.

Multi-speaker models are 1 unified model, but there are extra parameters for speaker embeddings. The `gin_channels` parameter controls this. I've found that when all of the speakers come from the same recording environment, a multi-speaker model works well. But in other cases where they come from different datasets, it can sound bad.
