### ISSUE TITLE
Multi-speaker models

### ISSUE THREAD

**Issue by fivestones** [rhasspy/piper#29]
How do we know if a model is a multi-speaker model (other than just trying to use it as one). Is there some documentation for a given model about if it is a single or multi-speaker model, and if a multi-speaker model, how many speakers it has?

Thanks!

**Comment by fivestones** [comment]
Also--I was experimenting with the en-us-libritts-high.onnx voice. I tried it will the --speaker <number> option and got up to 904 before it erred on me. And it seems to also work with negative numbered speaker numbers?

Are there really almost a thousand different voices encoded in that single 131 MB onnx file? What am I missing?

**Comment by synesthesiam** [comment]
The `num_speakers`  value in the model's JSON config file will tell you how many speakers are present. The LibriTTS voice has 904 speakers, so `--speaker 0` to `--speaker 903` are valid. The negative indexes are a weird quirk of the embedding used to represent speakers; not sure why PyTorch does this.

> Are there really almost a thousand different voices encoded in that single 131 MB onnx file? What am I missing?

There are! Well, there are 904 speaker vectors present. The speakers share most of the voice model's parameters, which is how they're all able to fit. You'll also find that as you go up in speaker numbers, the quality of the voice gets lower. This is because I order speakers by how much data is present during preprocessing, so speaker 0 will have the most data.

**Comment by thewh1teagle** [comment]
@synesthesiam 
Is it possible to fine tune multi speaker model with new single voice while preserving the rest of the voices in the model?

**Comment by synesthesiam** [comment]
No, you have to overwrite at least one speaker unfortunately. If it's one of the standard Piper voices, I arranged the speakers in order from most data to least data, so it's best to overwrite the last speaker.

**Comment by thewh1teagle** [comment]
@synesthesiam 
I tried that, but I noticed that all the voices then have the same new voice that I trained. is that normal?

What I did:
1. downloaded the libritts_r checkpoint
2. preprocess
3. added speaker_id as `7` in dataset.jsonl 
4. overwrited the config in `./train` to be like the original model (I don't have special phonemes)

Then I trained and checked after like 10 minutes and most of the voices was like the single voice I train on
