### ISSUE TITLE
Missing phonemes in Japanese

### ISSUE THREAD

**Issue by SchweitzerGAO** [rhasspy/piper#344]
I am trying to train a Japanese TTS model using [piper](https://github.com/rhasspy/piper) with espeak-ng as a phonemizer backend, I encountered this when I am processing the dataset. Is there any solutions?

![image](https://github.com/espeak-ng/espeak-ng/assets/64410968/ddb23171-0e07-42be-a77b-19ccc155adb4)

I am on Ubuntu 22.04.

**Comment by SchweitzerGAO** [comment]
Use espeak directly will solve the problem and the TTS model will work

**Comment by synesthesiam** [comment]
@SchweitzerGAO It looks like I may need to add some more phonemes to Piper. Without this, some words won't be pronounced correctly.

**Comment by masterwang22327** [comment]
@synesthesiam have you added the missing phonemes?

**Comment by masterwang22327** [comment]
@SchweitzerGAO hello,i download 1.48.04-espeak-source.zip and i find there is no ja_dict.how you success changed the data?just replace ja_dict or replace the whole piper_phonemize/espeaker-ng-data folder. look for your reply.

**Comment by masterwang22327** [comment]
@SchweitzerGAO ok. now i have some conclusion：
1.the old espeak repo not support japanese.so the solution is not using the original espeak.
2.replace phonemize dict?but i have not found espeak-ng have the same name file ja_dict?
3.using espeak-ng commandline processed the text instead of using piper_phonemize_cpp sdk?
