### ISSUE TITLE
Doubts About Training Time

### ISSUE THREAD

**Issue by JeditPro** [rhasspy/piper#396]

**Comment by rmcpantoja** [comment]
Hi @JeditPro.
To train from scratch, you need colab pro or pro+, because you need a machine to work with long time (24 hours max). To see how is going the model from scratch, you can see through tensorBoard.
Fine-tunning depends on the dataset but can take 4-6 hours to get good results. You can see tensorBoard in this case too.
Continue training is available if version 0 exists.
