### ISSUE TITLE
[ASK] How to Train With Own Voice

### ISSUE THREAD

**Issue by azkadev** [rhasspy/piper#41]
I tried to train using my voice from the mimic recording studio recordings

![Screenshot from 2023-04-17 13-41-21](https://user-images.githubusercontent.com/82513502/232404586-403dea2b-7803-4968-978f-4d8224f63056.png)

 
but when I try this command

```bash
python3 -m piper_train.preprocess --language id-id --input-dir ./f72022ff-93d3-6492-3f58-0a7eabfa98db/ --output-dir ./training_dir/ --dataset-format mycroft --sample-rate 22050
```

This error appears

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/galaxeus/Documents/hexaminate/app/piper/src/python/piper_train/preprocess.py", line 320, in <module>
    main()
  File "/home/galaxeus/Documents/hexaminate/app/piper/src/python/piper_train/preprocess.py", line 94, in main
    assert num_utterances > 0, "No utterances found"
AssertionError: No utterances found
```
 
How to solve this? What is wrong? sorry I'm still new to python

**Comment by azkadev** [comment]
> Hi @azkadev , did you find a solution for this error?

i've been trying for a long time, and it works, but now i forgot how to do it, i've switched from piper to openvoice/melotts
https://github.com/myshell-ai/MeloTTS

**Comment by OMVMMG** [comment]
@azkadev Thank you.

**Comment by coffeecodeconverter** [comment]
the error
~~~~~~~~~~~~~~~~~~~~~~~
AssertionError: No utterances found
~~~~~~~~~~~~~~~~~~~~~~~

means it cannot locate the utterances (.wav files) for one reason or another. 

could be because you dont have this specific folder structure:

    wav
        0000000001.wav
        0000000002.wav
        etc...
    metadata.csv
    
it could be because the file path and name is incorrect in the metadata.csv as the first column denotes the filename
for example this wont find the files because the names are wrong (taking the example above) 

audio1.wav|test utterance 1
audio2.wav|test utterance 2

but this would work 

0000000001.wav|test utterance 1
0000000002.wav|test utterance 2


it could be the contents of the CSV for example, a multi speaker takes 3 x columns, where 2nd column is the speaker name

0000000001.wav|speaker|test utterance 1
0000000002.wav|speaker|test utterance 2

you might have it blank 

0000000001.wav| |test utterance 1
0000000002.wav| |test utterance 2

but a single speaker is only 2 x columns, just filename|utterance 

the CSV could be in the wrong format, so it fails to parse the metadata and therefore fails to find the file / utterance.
