### ISSUE TITLE
What is the process to add a new voice in a language?

### ISSUE THREAD

**Issue by baldarn** [rhasspy/piper#65]
I would like to contribute adding new voices in italian ;)

**Comment by Giuliointhetube** [comment]
Me too!

**Comment by Shulyaka** [comment]
See #51

**Comment by baldarn** [comment]
Thank you @Shulyaka !

I did everything, but I don't have a corups available to start recording.

what corpus was used for italian? can you provide that?

If if have time I could do a PR in the mimic recorder to address multiple languages. now is suited for english, but i kind of hard to have other languages

**Comment by Shulyaka** [comment]
I am not sure about this actually. Could ChatGPT create a corpus?

**Comment by baldarn** [comment]
lol! I was going to use that with the english one to generate the italian XD

but, as an italia voice is there, I assume a corpus is there. ;)

**Comment by synesthesiam** [comment]
Good news! I've created [Piper Recording Studio](https://github.com/rhasspy/piper-recording-studio), which includes an Italian corpus (originally from [Microsoft](https://github.com/Azure-Samples/Cognitive-Speech-TTS/tree/master/CustomVoice/script/Italian%20(Italy)_it-IT)).

I've also created a website to collect voice data from volunteers at https://contribute.rhasspy.org/
Send me an e-mail at voice@nabucasa.com if you'd like to get a login code and contribute :slightly_smiling_face:

**Comment by Shulyaka** [comment]
Aren't they too small? 300-500 phrases vs 10 000 - 15 000?

**Comment by synesthesiam** [comment]
All together, there are about 1,150 phrases. This seems to be enough when fine-tuning from a related voice, but I suspect this will end up being very language-specific.

For now, I'm collecting these samples from volunteers, training voices, and then seeing if native speakers can hear any missing sounds in the results. If so, we'll add more sentences to the scripts to compensate and record a few more samples.

**Comment by fivestones** [comment]
Would it be possible to change some of the phrases to be multi-sentence? I only tried a few so far, but what I got were all single sentences. One of the problems I've encountered when trying to use piper on longer text samples is that the pacing is wrong much of the time where one sentence ends and another beginnings. (E.g., after a period there will be too short of a pause before the next sentence starts and this one thing makes it sounds pretty bad when trying to listen to it.) I'm guessing that's because the training data contains few or no samples with multiple sentences (or the end of one sentence leading into the next sentence all in one sample recording). So I'm assuming that if you had a voice that is trained on a corpus which includes multiple sentences, the pacing problem would be fixed.

Maybe I should make a separate issue for this but since people were discussing the corpus and you announced your new piper recording studio (Thanks!) I thought I'd stick it here for now.
